//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdapterSource) DeepCopyInto(out *AdapterSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdapterSource.
func (in *AdapterSource) DeepCopy() *AdapterSource {
	if in == nil {
		return nil
	}
	out := new(AdapterSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfig) DeepCopyInto(out *DeploymentConfig) {
	*out = *in
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfig.
func (in *DeploymentConfig) DeepCopy() *DeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadedAdapter) DeepCopyInto(out *LoadedAdapter) {
	*out = *in
	if in.LoadTime != nil {
		in, out := &in.LoadTime, &out.LoadTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadedAdapter.
func (in *LoadedAdapter) DeepCopy() *LoadedAdapter {
	if in == nil {
		return nil
	}
	out := new(LoadedAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoraAdapter) DeepCopyInto(out *LoraAdapter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoraAdapter.
func (in *LoraAdapter) DeepCopy() *LoraAdapter {
	if in == nil {
		return nil
	}
	out := new(LoraAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoraAdapter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoraAdapterList) DeepCopyInto(out *LoraAdapterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoraAdapter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoraAdapterList.
func (in *LoraAdapterList) DeepCopy() *LoraAdapterList {
	if in == nil {
		return nil
	}
	out := new(LoraAdapterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoraAdapterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoraAdapterSpec) DeepCopyInto(out *LoraAdapterSpec) {
	*out = *in
	out.AdapterSource = in.AdapterSource
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoraAdapterSpec.
func (in *LoraAdapterSpec) DeepCopy() *LoraAdapterSpec {
	if in == nil {
		return nil
	}
	out := new(LoraAdapterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoraAdapterStatus) DeepCopyInto(out *LoraAdapterStatus) {
	*out = *in
	if in.LoadedPods != nil {
		in, out := &in.LoadedPods, &out.LoadedPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodAssignments != nil {
		in, out := &in.PodAssignments, &out.PodAssignments
		*out = make([]PodAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoadedAdapters != nil {
		in, out := &in.LoadedAdapters, &out.LoadedAdapters
		*out = make([]LoadedAdapter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoraAdapterStatus.
func (in *LoraAdapterStatus) DeepCopy() *LoraAdapterStatus {
	if in == nil {
		return nil
	}
	out := new(LoraAdapterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAssignment) DeepCopyInto(out *PodAssignment) {
	*out = *in
	out.Pod = in.Pod
	if in.Adapters != nil {
		in, out := &in.Adapters, &out.Adapters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAssignment.
func (in *PodAssignment) DeepCopy() *PodAssignment {
	if in == nil {
		return nil
	}
	out := new(PodAssignment)
	in.DeepCopyInto(out)
	return out
}
